### ISSUE TITLE
Create workflow for macOS with openMP-support

### ISSUE THREAD

**Issue by serkor1** [serkor1/SLmetrics#47]
## :books: What?

Create a workflow for macOS that works optimally, so the package can be tested on all OS with and without OpenMP.

## :hammer_and_wrench: Current (semi-working) setup

```yaml
# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [development, macOS-openMP]
  pull_request:
    branches: [development, macOS-openMP]

name: macOS-llvm

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: macOS-llvm

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,    r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install xcode
        run: |
          sudo softwareupdate --list
          sudo softwareupdate --install "Command Line Tools for Xcode-<16.2>"
          brew install gcc
      - name: Install OpenMP
        run: |
          curl -O https://mac.r-project.org/openmp/openmp-18.1.8-darwin20-Release.tar.gz
          sudo tar fvxz openmp-18.1.8-darwin20-Release.tar.gz -C /
      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Configure OpenMP in R
        run: |
          mkdir -p ~/.R
          XCBASE=$(xcrun --show-sdk-path)
          GCCBASE=$(brew --prefix gcc)
          GETTEXT=$(brew --prefix gettext)
          GCCVERSION=$(find "${GCCBASE}/bin" -type f -name "gcc-[0-9]*" | sed "s/[^-]*-//")
          
          cat << EOF > ~/.R/Makevars
          CC=${GCCBASE}/bin/gcc-${GCCVERSION}
          CXX=${GCCBASE}/bin/g++-${GCCVERSION}
          CXX11=${GCCBASE}/bin/g++-${GCCVERSION}
          CXX14=${GCCBASE}/bin/g++-${GCCVERSION}
          CXX17=${GCCBASE}/bin/g++-${GCCVERSION}
          CXX1X=${GCCBASE}/bin/g++-${GCCVERSION}
          
          CPPFLAGS=-isystem "${GCCBASE}/include" -isysroot "${XCBASE}"
          LDFLAGS=-L"${GCCBASE}/lib" -L"${GETTEXT}/lib" --sysroot="${XCBASE}"
          
          FC=${GCCBASE}/bin/gfortran
          F77=${GCCBASE}/bin/gfortran
          FLIBS=-L${GCCBASE}/lib/gcc/${GCCVERSION}/ -lm -lgfortran
          EOF
          echo 'CPPFLAGS  += -fopenmp' >> ~/.R/Makevars
          echo 'LDFLAGS += -lomp' >> ~/.R/Makevars
          
        shell: bash


      - name: Installing {pkgs}
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck reticulate
          needs: check

      - name: Setup Python and {reticulate}
        uses: ./.github/actions/setup-reticulate

      - name: Debug Environment
        run: |
          echo "Debugging Environment"
          cat ~/.R/Makevars
          Rscript -e "pkgbuild::check_build_tools(debug = TRUE)"
      - name: R CMD check
        uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual", "--compact-vignettes=gs+qpdf")'
```

From the unit-tests in R CMD checks for macOS:

```
  OpenMP usage set to: enabled
  OpenMP usage set to: enabled
  OpenMP usage set to: enabled
  OpenMP usage set to: enabled
  OpenMP usage set to: enabled
  OpenMP usage set to: enabled
  OpenMP usage set to: enabled
  OpenMP usage set to: enabled
  OpenMP usage set to: enabled
  OpenMP usage set to: disabled
  OpenMP usage set to: disabled
  OpenMP usage set to: disabled
  OpenMP usage set to: disabled
  OpenMP usage set to: disabled
  OpenMP usage set to: disabled
  OpenMP usage set to: disabled
  OpenMP usage set to: disabled
  OpenMP usage set to: disabled
  OpenMP usage set to: enabled
  OpenMP usage set to: enabled
  OpenMP usage set to: enabled
  OpenMP usage set to: enabled
  OpenMP usage set to: enabled
  OpenMP usage set to: enabled
  OpenMP usage set to: enabled
  OpenMP usage set to: enabled
  OpenMP usage set to: enabled
  OpenMP usage set to: disabled
  OpenMP usage set to: disabled
  OpenMP usage set to: disabled
  OpenMP usage set to: disabled
  OpenMP usage set to: disabled
  OpenMP usage set to: disabled
  OpenMP usage set to: disabled
  OpenMP usage set to: disabled
  OpenMP usage set to: disabled
```

However, the R CMD check doesn't finish: I decided to cancel it after *47 minutes*.
